version: '3.2'
services:
  app:
    build: .
    command: flask run --host=0.0.0.0
    tty: true
    stdin_open: true
    ports:
      - 5000:5000
    container_name: recipes
    volumes:
      - .:/app
    environment:
      FLASK_APP: /app/app.py

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: development
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
