version: '3.2'
services:
  app:
    build: .
    command: flask run --host=0.0.0.0
    tty: true
    stdin_open: true
    ports:
      - "5000:5000"
    container_name: recipes
    volumes:
      - .:/app
    environment:
      FLASK_APP: /app/app.py
      FLASK_ENV: development

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: development
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./sql:/var/lib/postgresql/sql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: sq22@duke.edu
      PGADMIN_DEFAULT_PASSWORD: test
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "8080:80"
